---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: mcp-master-wait-job
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - image: quay.io/openshift/origin-cli:4.11
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/mcp
              echo ""
              echo -n "Waiting for the MCP $MCP to converge."
              sleep $SLEEP
              ## Could also use `kubectl`
              until oc wait --for condition=updated --timeout=60s mcp $MCP
              do
                echo -n "...still waiting for $MCP to converge"
                sleep $SLEEP
              done
              echo "DONE"
          imagePullPolicy: Always
          name: mcp-master-wait-job
          env:
          - name: SLEEP
            value: "5"
          - name: MCP 
            value: master
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30
