apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: bgd-cli-wait
spec:
  template:
    spec:
      containers:
        - image: quay.io/openshift/origin-cli:4.11
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/cli
              echo ""
              echo -n "Waiting for deployment"
              sleep $SLEEP
              ## Cloud also use `kubectl`
              until oc wait --for condition=complete --timeout=30m jobs/guestbook-cli-wait -n guestbook 2>&1 >/dev/null
              do
                echo -n "."
                sleep $SLEEP
              done
              echo -n -e "DONE\n"
          imagePullPolicy: Always
          name: oc-wait-container
          env:
          - name: SLEEP
            value: "15"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccountName: cli-job-sa-bgd
      terminationGracePeriodSeconds: 90
